### ISSUE TITLE
Presentación del curso

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#1]
![](http://i.imgur.com/CfSwf.jpg)

# Presentación de curso

Esta asignatura aporta al perfil del Ingeniero en Sistemas Computacionales las siguientes habilidades:

*  Implementa aplicaciones computacionales para solucionar problemas de diversos contextos, integrando diferentes tecnologías, plataformas o dispositivos.

*  Desarrolla y administra software para apoyar la productividad y competitividad de las organizaciones cumpliendo con estándares de calidad.

*  Coordina y participa en equipos multidisciplinarios para la aplicación de soluciones innovadoras en diferentes contextos.

*  Diseña e implementa interfaces para la automatización de sistemas de hardware y desarrollo del software asociado.

La presente asignatura aporta los conocimientos para el diseño e implementación de interfaces hombre- máquina y máquina-máquina para la automatización de sistemas. El desarrollo, implementación y administración de software de sistemas o de aplicación que cumpla con los estándares de calidad con el fin de apoyar la productividad y competitividad de las organizaciones. Para que desempeñe sus actividades profesionales considerando los aspectos legales, éticos, sociales y de desarrollo sustentable y a la vez le permita poseer las habilidades metodológicas de investigación que fortalezcan el desarrollo cultural, científico y tecnológico en el ámbito de sistemas computacionales y disciplinas afines.

# Presentación Docente

_El curso es muy especial, ya que involucra conocer las tendencias de los Gadgets para comprender el uso de los MCU y sensores, así lograr establecer una linea de productos de innovación y diseño de los mismos. Esta muy interesante comprender el funcionamiento del procesador móvil ARM y lo importante que es hoy en dia._ René

[](http://nebula.wsimg.com/4eb9a6b44ccd3615e8b17c3f083cd7e4?AccessKeyId=101858493875673E726C&disposition=0&alloworigin=1)

# Temario Oficial
[O ISIC-2010-224 Lenguajes de Interfaz.pdf](https://github.com/tectijuana/interfaz/files/698093/O.ISIC-2010-224.Lenguajes.de.Interfaz.pdf)

# Evaluación 
Las evaluaciones por _project based competency_ , se asignan las participaciones y sus respectivas rúbricas, todo documentado y redactado en ISC7Drive o aqui mismo en los casos de GitHUB. La sabana es electrónica y se presentan las calificaciones con su retroalumentación.

 # Trabajos de redacción
Estamos trabajando con templetes de LaTeX via http://tinyurl.com/isc7tareas _(deseable registrarse con GMail)_ con citación estilo Harvard por BibTeX via Mendeley (https://es.wikipedia.org/wiki/Mendeley) y/o Google Scholar.

# Recomendaciones 
Realmente *no faltar y trabajar en equipo*, verdaderamente ponerse de acuerdo con los compromisos y relizarlos, no atenerse y trabajar por su sección que acordo con sus colegas. Los equipos pueden ser aleatorios por el docente, y en ocaciones propios de Uds. la idea es que sea dinámico.

# Participaciones (Slack)
Trabajamos via invitación por http://isc7.slack.com (https://es.wikipedia.org/wiki/Slack_%28software%29) para atender los detalles de curso, y evidencias por aplicación móvil. Aclarar dudas fuera de horario y claro en un ambiente de productividad por por BOTS  ejemplo _"busyBot"_. Esta para Linux, Windows, macOS, Android y iOS, gratis.

# Acuerdos especificos para el grupo.
En este párrafo se pondrán detaller especificos del grupo sobre la marcha para recordatorio ante todos.

**Comment by IoTeacher** [comment]
# Temario Oficial
[O ISIC-2010-224 Lenguajes de Interfaz.pdf](https://github.com/tectijuana/interfaz/files/698093/O.ISIC-2010-224.Lenguajes.de.Interfaz.pdf)

**Comment by IoTeacher** [comment]
**Evaluación por competencias**
_Para evaluar las actividades de aprendizaje se recomienda solicita_r: Resumen, Mapa Mental, Mapa
Conceptual, Mapa Cognitivo, Tabla Comparativa, Línea de Tiempo, Examen, Reporte de conclusiones
grupales, Reporte de práctica de laboratorio.
_Para verificar el nivel de logro de las competencias del estudiante se recomienda utilizar_: Rubricas,
Registro anecdótico, Guía de observación, Matriz de valoración, Lista de cotejo, Guía de proyecto,
Videos.

**Comment by IoTeacher** [comment]
## _Favor de llenar los datos que faltan de su parte, gracias_
| Matricula 	| Nombre                                  	| Slack 	| GitHub 	|
|-----------	|-----------------------------------------	|-------	|--------	|
| 14210486  	| AQUINO ACUÑA CARLOS RAFAEL              	|       	|        	|
| 14210428  	| CELAYA CARRANCO FAUSTO JAVIER           	|       	|        	|
| 14210475  	| CHIPRES CASTELLANOS ANA MARIA           	|       	|        	|
| 14210482  	| CRESPO CORONADO JAZMIN ESMERALDA        	|       	|        	|
| 12211840  	| FLORES PACHECO EMANUEL                  	|       	|        	|
| 14212020  	| GALEANA FRIAS EZEQUIEL                  	|       	|        	|
| 11210312  	| GARCIA CARDENAS YAMIRA                  	|       	|        	|
| 14211429  	| GARCIA PEREZ ALAN                       	|       	|        	|
| 12210376  	| GUTIERREZ PATIÑO DYLCIA ESTEFANIA       	|       	|        	|
| 14212028  	| HERNANDEZ BARRIOS ERIC HARIM            	|       	|        	|
| 14212379  	| HERNANDEZ LEON DIEGO KEVIN              	|       	|        	|
| 14212031  	| HINOJOSA COVARRUBIAS ALEJANDRO UZIEL    	|       	|        	|
| 14210508  	| LAGUNA HERNANDEZ BIRIDIANA              	|       	|        	|
| 13211502  	| LOPEZ VALENZUELA MARCO ANTONIO          	|       	|        	|
| 14210477  	| LORENZO DEMUNER JOSE JORDAN             	|       	|        	|
| 16211345  	| LUQUIN CASTILLO CESAR ARTURO            	|       	|        	|
| 14211451  	| MARQUEZ ENRIQUEZ JOSE MANUEL            	|       	|        	|
| 14210427  	| MUNIVE SALDAÑA EVANS JOSUE              	|       	|        	|
| 14210423  	| PASILLAS LUIS MIGUEL ANGEL              	|       	|        	|
| 14210433  	| PEREZ BERNAL ARTURO                     	|       	|        	|
| 13210717  	| PEREZ CABRERA JULIO CESAR               	|       	|        	|
| 14212261  	| PEREZ CASTAÑEDA JONATHAN GERARDO        	|       	|        	|
| 14212051  	| QUEZADA NEVAREZ RODOLFO ALFREDO         	|       	|        	|
| 14211469  	| REYES GONZALEZ RIGOBERTO                	|       	|        	|
| 14210454  	| RIOS OROPEZA EDGAR ALEJANDRO            	|       	|        	|
| 14210437  	| RODRIGUEZ ROJAS ANTHON BRAYAN           	|       	|        	|
| 14210438  	| ROMERO VEGA ANDREA CAROLINA             	|       	|        	|
| 14210489  	| ROSALES PINEDA ANGEL                    	|       	|        	|
| 13210347  	| RUIZ LEA GERMAN SALVADOR                	|       	|        	|
| 13210413  	| SANTILLAN GIL SAUL IVAN                 	|       	|        	|
| 14211483  	| SILVA BAUTISTA ALEXIS EDUARDO           	|       	|        	|
| 13210388  	| TORRES FLORES IVAN ADRIAN               	|       	|        	|
| 14212066  	| VELASCO CALIXTO JOSE ARMANDO            	|       	|        	|
| 14212265  	| VERDI VEGA EVELIN                       	|       	|        	|
| 14210434  	| VILLAGOMEZ DOMINGUEZ MARCOS EDUARDO     	|       	|        	|
| 13211450  	| VILLANUEVA HERNANDEZ FRANCISCO JONATHAN 	|       	|        	|
| 14211495  	| VIVANCO GARCIA JOEL                     	|       	|        	|

**Comment by jc0511** [comment]
+# Title: HELLO WORLD en Simulador ARM	Filename: p0-holamundo.s
+# Author: Rios Oropeza Edgar Alejandro	Date: 2 / Feb / 2017
+# Description: Mostrar HELLO WORLD
+# Input: -HELLO WORLD
+
+.global _start
+############################# Code segment ####################################
+_start:

MOV R7, #4 ###;- cargar el valor de datos que esta en esta posicion en la secuencia de instrucciones
MOV R0, #1 ###;- cargar el valor de datos que esta en esta posicion en la secuencia de instrucciones
MOV R2, #12 ###;- parametro
LDR R1, =string ###parametro y direccion de la cadena
SWI 0 ### señal de interrupcion al O.S.
MOV R7, #1 ### salir del programa y matar el proceso
SWI 0 ### señal de interrupcion al O.S. para la terminacion
+############################# Data segment ###################################
.data
+string:
.ascii "HELLO WORLD"

**Comment by IoTeacher** [comment]
![screen shot 2017-03-25 at 9 30 20 pm](https://cloud.githubusercontent.com/assets/2523851/24328632/26cecb24-11a3-11e7-8206-7ab32e44f485.png)
