### ISSUE TITLE
1.2.2 Ejercicios de ASM 8bit a C standard

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#17]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/ec1a0b80-6d7f-4b53-ab8f-b3ab33fff3f6)

Acceder a una maquina simple 8-bits emulada.

# Utilizar los GTP´s para documentar el código fuente del emulador de 8-bits

# Es libre de cuestionar cualquier duda por el GTP

Aquí tienes una versión de la actividad de laboratorio en formato Markdown para GitHub:

---

# Actividad de Laboratorio de Computación: Conversión de ASM a C

## Objetivo
El objetivo de esta práctica de laboratorio es familiarizarse con la programación en lenguaje ensamblador (ASM) de 8 bits y su conversión a lenguaje C estándar. Los estudiantes aprenderán a manipular y modificar muestras de código, así como a comprender la documentación de mnemónicos e instrucciones de un emulador específico.

## Fuente:
- https://cpu.visualrealmsoftware.com/emu/

## Requisitos Previos
- Conocimientos básicos de programación en C y lenguaje ensamblador.
- Acceso a un entorno de desarrollo de C y a un emulador de ASM de 8 bits.

### 1. Revisión de Documentación
- Inicie la actividad leyendo la documentación proporcionada sobre el emulador de ASM de 8 bits utilizado en este laboratorio. Preste especial atención a los mnemónicos (abreviaturas de instrucciones) disponibles y a sus respectivas funciones.

### 2. Análisis de Mnemónicos
- Elija cinco mnemónicos del conjunto de instrucciones y describa brevemente su propósito y cómo se utilizan en programas de ASM.

### 1. Selección de Muestras de Código ASM
- Utilizando las muestras de código ASM proporcionadas por el instructor, seleccione tres fragmentos de código para trabajar. Asegúrese de que cada muestra incluya varios mnemónicos diferentes.
- Pida a el GTP le agregue comentarios detallados de lo que sucede linea por linea.
- 

### 2. Análisis del Código ASM
Para cada fragmento de código seleccionado, realice lo siguiente:
  a. Identifique y describa el propósito del código.
  b. Anote los mnemónicos utilizados y su función en el contexto del código.

### 3. Conversión a C
- Convierta cada muestra de código ASM a lenguaje C estándar. Asegúrese de mantener la funcionalidad original del código ASM en su versión en C.

### 4. Comparación y Análisis
- Compare el código original en ASM con su versión convertida en C. Discuta las diferencias en términos de sintaxis, legibilidad y eficiencia.

### 1. Manipulación del Código
- Modifique las versiones en C de las muestras de código para alterar su comportamiento. Esto puede incluir cambios en la lógica, la implementación de nuevas características o la optimización del código.

### 2. Pruebas y Validación
- Compile y ejecute las versiones modificadas del código en C. Verifique que funcionen según lo previsto y documente cualquier cambio en el comportamiento del programa.

## Entrega GIST personal
- Un informe que incluya:
  - La descripción y análisis de los mnemónicos seleccionados.
  - El código ASM original y su versión convertida a C para cada muestra de 8-bit computer.
  - Una discusión sobre las diferencias entre las versiones ASM y C.
  - El código modificado en C y una descripción de los cambios realizados.
  - Conclusiones sobre la experiencia de conversión de código y su manipulación.

## Evaluación
La evaluación de esta actividad se basará en la precisión de la conversión del código, la creatividad en las modificaciones realizadas al código en C y la profundidad del análisis y discusión en el informe.

![Image](https://github.com/tectijuana/interfaz/assets/2523851/15fa1861-ab49-4051-9bc0-1ba7e5789070)

**Comment by IoTeacher** [comment]
RESALTAR CODIGO DE BLOQUE

```javascript
function test() {
  console.log("notice the blank line before this function?");
}
```

(triplecomilla) ```javascript
function test() {
  console.log("notice the blank line before this function?");
}

(triplecomilla)```

**Comment by IoTeacher** [comment]
```asm
; FACTORIALS
;
; Cycles through factorial numbers (0! -> 5!)

.begin:
	data Rd, 1
	data Ra, 0
	push Ra
	inc Ra

.next:
	pop Rc
	inc Rc
	push Rc
	mov Rd, Ra
	mov Rb, Ra

.mul:
	add Ra
	jc .end
	dec Rc
	jz .next
	jmp .mul

.end:
	pop Rc
	jmp .begin
```

**Comment by IvanVG7** [comment]
"""c++
#include <iostream>
using namespace std;

// Función para verificar si un número es primo
int esPrimo(int numero) {
    int mayorFactor = numero; // Inicializa mayorFactor con el número en sí mismo

    // Itera de 7 hacia abajo hasta 1
    for (int divisor = 7; divisor > 0; --divisor) {
        // Verifica si el divisor divide uniformemente el número
        while (numero % divisor == 0) {
            // Si lo hace, actualiza mayorFactor y reduce el número
            mayorFactor = divisor;
            numero /= divisor;
        }
    }

    // Si mayorFactor no es el número en sí mismo, devuelve mayorFactor
    if (mayorFactor != numero)
        return mayorFactor;
    // Si mayorFactor es el número en sí mismo, devuelve 1 indicando que es primo
    else
        return 1;
}

int main() {
    int numero = 21; // Cambia este número para probar si es primo

    // Llama a la función esPrimo para verificar si el número es primo
    int resultado = esPrimo(numero);

    // Imprime el resultado
    if (resultado == 1)
        cout << numero << " es primo." << endl;
    else
        cout << numero << " no es primo. Su mayor factor es " << resultado << "." << endl;

    return 0;
}
"""c++

**Comment by SantyDebian** [comment]
Martínez Castellanos Santy Francisco
https://gist.github.com/SantyDebian/41fee9234db0c79af9f08a8e1ffe1ad1

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/79c476e2-aa72-454a-b71e-b50a07b24500)


https://github.com/tectijuana/interfaz/tree/master/templete

**Comment by IoTeacher** [comment]
[problemas_para_resolver_por_computadora.pdf](https://github.com/tectijuana/interfaz/files/14454077/problemas_para_resolver_por_computadora.pdf)

**Comment by fragojor** [comment]
Gist Ejercicio 29 febrero:
https://gist.github.com/fragojor/23af553a2d6e3257fb1c068a79937169

**Comment by IoTeacher** [comment]
@frag

> Gist Ejercicio 29 febrero: https://gist.github.com/fragojor/23af553a2d6e3257fb1c068a79937169

Solo falta su programa.  El
Que presentó ya estaba hecho solo comentado en español

**Comment by EddieReynosoR** [comment]
Gist Programa en ASM

Reynoso Rosales Eduardo Guadalupe - 21212036
Soto Sanchez Yahir Jasiel - 21212055

https://gist.github.com/EddieReynosoR/9d25b5b2de4e3b5c4896db906bb9088e

**Comment by EddieReynosoR** [comment]
Reynoso Rosales Eduardo Guadalupe 21212036
Soto Sanchez Yahir Jasiel 21212055

https://gist.github.com/EddieReynosoR/9d25b5b2de4e3b5c4896db906bb9088e

**Comment by AbrahamAganza** [comment]
Aganza Molina Abraham Armando 19210455
Suma simple de dos registros de forma no continua
https://gist.github.com/AbrahamAganza/51333b879dadf0501b6f0066e31f5d73

**Comment by Shouko07** [comment]
Montaño Zaragoza Marcos Ulises 
Garcia Cortez Kevin Eduardo
Programa que toma un numero dado y de manera infinita le suma un segundo numero, mientras en la pantalla LCD se imprime Resultado
https://gist.github.com/Shouko07/4ddf9ad2be587e62e9b8092f61abc93e

**Comment by ObedVPSM256** [comment]
**Velazquez Pizarro Mixcoatl Obed - 21212062
Bañuelos Vazquez Eduardo Daniel**

**Programa que contea del 9 al 45**
https://gist.github.com/ObedVPSM256/a3ff4bc95476468e1f2968d73498a073

**Comment by cristianHernandezVITT** [comment]
Hernández Vázquez Cristian

Morales López Billi Joel

Sáchez Tolentino Gerardo Julián

Pérez López Saúl
Programa que cuenta los números del 9 al 43
https://gist.github.com/cristianHernandezVITT/89356e43f47406ca4cb3cb875203efd1

**Comment by YessMtz** [comment]
Martinez Nava Blanca Yessenia
Programa que cuenta los números de 2 al 48
https://gist.github.com/YessMtz/4a53b8432407bfe53adf928e702cbf73.js
