### ISSUE TITLE
Equipo 1 - Emulador de videojuegos  GameConsole-Pi

### ISSUE THREAD

**Issue by gammarg** [tectijuana/interfaz#19]
# **GameConsole-Pi**

**Integrantes:**
                    -Alvarado Albares Edgar Eliud (@ealvaradoa)
                    -Alvarez Lapizco Miguel Angel (@mizusu)
                    -Reyes Gutierrez Gamaliel (@gammarg)
                    -Espinoza Covarrubias Alejandro(@alejandro-espinoza)

**Proyecto:** Emulador de videojuegos utilizando una Raspberry pi, se conectaria un control con entrada usb(xbox, playstation o standard) a la raspberry, a su vez esta se conectaria a un monitor para desplegar la imagen.

**Comment by ealvaradoa** [comment]
https://www.pine64.pro/getting-started-android/  info revisar

**Comment by ealvaradoa** [comment]
https://www.pine64.pro/

**Comment by IoTeacher** [comment]
Se mueve a Gestion de Proyectos
