### ISSUE TITLE
1. Introducción al lenguaje ensamblador

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#2]
# 1. Introducción al lenguaje ensamblador

**Comment by IoTeacher** [comment]
Contamos con varias fuentes, pero viendo en grande este video nos da un punto de partida.

<iframe width="560" height="315" src="https://www.youtube.com/embed/CDgtZSl_DII" frameborder="0" allowfullscreen></iframe>

**Comment by IoTeacher** [comment]
Este video nos da una visión de ARM Holding y su arquitectura RISC ahora ARM.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=7LqPJGnBPMM
" target="_blank"><img src="http://img.youtube.com/vi/7LqPJGnBPMM/0.jpg" 
alt="Fundamentos de la arquitectura ARM (RISC)" width="240" height="180" border="10" /></a>

**Comment by IoTeacher** [comment]
_Favor de teclear preguntas sobre el 2do. video, apoyándose mutuamente el grupo y mi persona las contestaremos,  las preguntas pueden ser formato abierto o en selección múltiple, con el fin de lanzar la concentración a estos 45 min; quedando la primera participación en este bloque._

(MarkDown debes de practicar) https://sourceforge.net/p/rubrics/wiki/markdown_syntax/


|               CATEGORIA               	|                                                                           4                                                                           	|                                                                             3                                                                             	|                                                                 2                                                                	|                                       1                                      	|
|:------------------------------------:	|:-----------------------------------------------------------------------------------------------------------------------------------------------------:	|:---------------------------------------------------------------------------------------------------------------------------------------------------------:	|:--------------------------------------------------------------------------------------------------------------------------------:	|:----------------------------------------------------------------------------:	|
| Identifica los Detalles              	| El estudiante recuerda varios detalles para cada punto importante sin referirse al artículo.                                                          	| El estudiante recuerda detalles para cada punto importante, pero necesita referirse al artículo ocasionalmente.                                           	| El estudiante puede localizar la mayoría de los detalles cuándo mira el artículo.                                                	| El estudiante no puede localizar detalles con precisión.                     	|
| Identifica Opiniones                 	| El estudiante localiza con precisión, por lo menos, 5 opiniones en el artículo y da una explicación clara de por qué éstas son opiniones y no hechos. 	| El estudiante localiza con precisión, por lo menos, 4 opiniones en el artículo y da una explicación razonable de por qué éstas son opiniones y no hechos. 	| El estudiante localiza con precisión, por lo menos, 4 opiniones en el artículo. su explicación es insuficiente.                  	| El estudiante tiene problemas localizando las opiniones en el artículo.      	|
| Identifica la Información Importante 	| El estudiante puede nombrar los puntos importantes del artículo sin tenerlo frente a sí mismo/a.                                                      	| El estudiante nombra todos los puntos importantes, pero usa el artículo de referencia.                                                                    	| El estudiante nombra todos los puntos menos uno, usando el artículo de referencia. El/ella no señala ningún punto no importante. 	| El estudiante no puede nombrar ninguna información importante con precisión. 	|

**Comment by elephannt** [comment]
# Preguntas del segundo video.

----
## Cuestionario.

#1. Cuales son las características de ARMv7-A?

> ** Soporte para administración de memoria.**

> ** Excelente performance con bateria baja. **

> ** Se ve influido por multi-tareas de sistemas operativos. **

#2. Cuales son las características de ARMv7-R?

> ** Memoria protegida.**

> ** Poco tiempo de espera.**

---

[Links used](https://www.youtube.com/watch?feature=player_embedded&v=7LqPJGnBPMM)

**Comment by elephannt** [comment]
# Preguntas del segundo video.

----
## Cuestionario.

# 1. Cuales son las características de ARMv7-A?

> **Soporte para administracion de memoria.**

> **Excelente performance con bateria baja.**

> **Se ve influido por multi-tareas de sistemas operativos.**

# 2. Cuales son las características de ARMv7-R?

> **Memoria protegida.**

> **Poco tiempo de espera.**

---

[Links used](https://www.youtube.com/watch?feature=player_embedded&v=7LqPJGnBPMM)

**Comment by jonathanvillanueva127** [comment]
# Actividad: Preguntas sobre ARM holding y arquitectura RISC ahora ARM

----
# 1.-Cuales son los modos de operación de  ARM?


----
# 2.-Para que se utiliza principalmente la tecnología ARM?

# 3.-Cuales son los perfiles de la arquitectura ARMV7-A?

**Comment by RodolfoQuezada** [comment]
# Cuestionario

#¿Cuales son las desventajas de la arquitectura ARM?#

#¿Existe algún software dedicado para la programación en ARM?#

#¿Cuales son las principales diferencias entre la arquitectura ARM y x86?#

**Comment by RodolfoQuezada** [comment]
#  **Cuestionario**

**¿Cuales son las desventajas de la arquitectura ARM?**

**¿Existe algún software dedicado para la programación en ARM?**

**¿Cuales son las principales diferencias entre la arquitectura ARM y x86?**

**Comment by vivanko** [comment]
# **Cuestionario**

**1.- ¿A partir de que versión de la arquitectura ARM se soporta Virtualización?**

**2.- ¿Cuál es el objetivo del diseño RISC?**

**3.- ¿Cuales son las 4 etapas en el manejo de excepciones?**

**Comment by Celayafj** [comment]
1.- ¿Que es ARM?
2.- ¿Que otros productos hacen ademas de nucleos de procesadores?
3.- ¿Cuantas plantas de ARM existen en todo el mundo?

**Comment by jazmincrespocoronado** [comment]
----
## ¿Cuáles son los 7 modos de funcionamiento básico de los núcleos?


> * SVC
> * FIQ
> * IRQ
> * abort
> * undef
> * system
> * user

----
## ¿Cuáles son las 2 zonas de confianza que proporciona el procesador?


> * Secure
> * Normal

----
## ¿Cuál es el conjunto de instrucciones de ARM?


> * Todas las instrucciones son de 32 bits
> * La mayoría de las instrucciones pueden ejecutarse >   de forma condicional
> * Conjunto de instrucciones de carga / almacenamiento sin manipulación directa

**Comment by PerezArturo** [comment]
# Preguntas Video

1. Que significa ARM?
> Advance Risc Machines
2. En que año fue fundada?
> 1990
3. Cuales son los procesadores clasicos de ARM?
> ARM7TDMI-S
> ARM946E-S

**Comment by pasillasangel** [comment]
## ¿Qué es lo que permite la Arquitectura de Perfiles (Architecture Perfiles)?

> Permite una arquitectura común única para apoyar la enorma desigualdad de los resultados y aplicación. Se hizo evidente que una arquitectura no podria proporcionar todo, desde el más pequeño microcontrolador para el más inteligente de los telefonos por lo que la arquitectura version 7 se introdujo la arquitectura Perfiles.

----
## ¿Qué es lo que permite modo adicional hypermode?

> Permite la implementación de un dispositivo hardware hipervisor de virtualizacion y se puede ver que el hipervisor se encuentra por encima del sistema y se puede configurar cosas de hardware y operativos invitados debajo como las exepciones y otros eventos del sistema para ser atrapado por el hipervisor.

----
## Menciona actividades que realiza la extensión de confianza. (TrustZone)

> * Permite implementación de plataformas seguras para cosas como la gestión de derechos digitales y soluciones de pago seguras.
* El diseñador del sistema puede crear periféricos seguros y regiones de memorias seguras.
* Evita las fugas de datos a través de la frontera SECURE y NORMAL.

**Comment by chipres** [comment]
---

### ¿Para que se utiliza el modo IRQ?
> Se utiliza para el manejo de nuestra señal que interrumpe el modo SVC , se utiliza para la manipulación.


### ¿Qué es una excepción en la arquitectura ARM?
>Una excepción es solo un tipo de evento que causa una interrupción en el flujo normal del programa mientras el sistema se ocupa de todo.

### ¿Qué es lo que tiene cada instrucción?
>Cada instrucción tiene un campo de condición que suprime su ejecución.

**Comment by EzequielGaleana** [comment]
1.-¿En que consiste ARM?
2.-¿Quién usa ARM?
3.-¿Cuáles son los tipos en ARM?

**Comment by AnthonRodriguez** [comment]
1.-¿En que año se fundo ARM?
1990
2.-¿Quién maneja la arquitectura ARM en su procesador?
Desde un principio fue la forma de diseña los microprocesador...
3.-¿Cuáles es la diferencia en los procesador corex a-15 y core A-7 ?
Funcionamiento interno en su microarquitectura..

**Comment by CarolinaRomero33** [comment]
1. ¿Porque surge ARM?
2. ¿Que tipo de arquitectura usa ARM?
3. ¿Que es el Thumb?
4. ¿Cuales son la excepciones de ARM?
FIQ
IRQ
Abort
Unidef
SVC
5. ¿Que es el FIQ?
Solicitud de interrupciones de alta prioridad

**Comment by IoTeacher** [comment]
Aquí se cierra la participación y tendrá la evaluación de 12 sobre el bloque 1. 
_Checar la rubrica en la parte superior._

**Comment by EvansMunive** [comment]
#  **Cuestionario y Comentario**
ARM es una tecnología que se ha retomado para dar poder a los nuevos dispositivos móviles y será este año cuando veamos realmente la competencia por demostrar quién será el lider dominante de ella.

**1.- ¿Cuando fue fundado ARM y que significan las siglas?**

**2.- ¿Cuáles son las 2 zonas de confianza que proporciona el procesador?**

**3.- ¿Cuáles son las desventajas de la arquitectura ARM?**

**Comment by Lou-Zar** [comment]
**Preguntas del video (a solicitud del maestro)**

**¿Que significa ARM?**
Advance Risc Machines

**¿En que año se fundo?**
En el año 1990

**¿Que es el FIQ?**
Solicitud de Interrupciones de Alta Prioridad

**Comment by IoTeacher** [comment]
![](https://images.cooltext.com/4894468.png)

<a href="http://cooltext.com" target="_top"><img src="https://cooltext.com/images/ct_pixel.gif" width="80" height="15" alt="Cool Text: Logo and Graphics Generator" border="0" /></a>

----
## Si esta Ud. Explorando esta sección **debe ver el SEGUNDO VIDEO y CONTESTAR 3 preguntas** de sus compañeros para lograr salvar por retraso

**Comment by biridianalaguna** [comment]
1.-¿Que significa ARM?
Advance Risc Machines.

2.-¿En que año fue fundada ARM?
1990.

3.-¿Cuales son las dos zonas de confianza que proporciona el procesador?
Secure, Normal.

**Comment by Josearmandovelascocalixto** [comment]
1.- ¿Que es el FIQ?
Solicitud de Interruptores de Alta Prioridad.
2.¿En que año se fundo ARM?
En el año 1990
3.-¿Que significa ARM?
Advance Risc Machines.
.

**Comment by AlejandroHinojosa** [comment]
Preguntas del Video:
     **Que significa ARM?**
    Advance Risc Machines
 **¿Cuales son la excepciones de ARM?**
FIQ
IRQ
Abort
Unidef
SVC
**Cuales son los procesadores clasicos de ARM?**
    ARM7TDMI-S
    ARM946E-S

**¿Cuál es el conjunto de instrucciones de ARM?**
        Todas las instrucciones son de 32 bits
        La mayoría de las instrucciones pueden ejecutarse > de forma condicional
        Conjunto de instrucciones de carga / almacenamiento sin manipulación directa

**Comment by ivanatorresf** [comment]
## **_¿Que tipo de arquitectura usa ARM?_**
ARM es una arquitectura RISC  (Reduced Instruction Set Computer=Ordenador con Conjunto Reducido de Instrucciones) de 32 bits y recientemente con la llegada de su versión V8-A también de 64 Bits
## **_2.-¿Quién usa ARM?_**
el desarrollo de los chips ARM ha sido gracias a distintos fabricantes como Qualcomm, Texas Instruments, Apple, Samsung … y muchos más. 
## **¿Cuál es el objetivo del diseño RISC?**_**
El objetivo de diseñar máquinas con esta arquitectura es facilitar el paralelismo en la ejecución de instrucciones y permitir realizar tareas menores con procesos más cortos lo que al final conlleva una disminución de la energía empleada.
