### ISSUE TITLE
Equipo 2: a)Radio Station con raspberry Pi/ b)Traductor Simultaneo (propuetas)

### ISSUE THREAD

**Issue by miriamvillagomez** [tectijuana/interfaz#20]
a)Radio Station
https://www.youtube.com/watch?v=Mcz7phI9H1A
http://kodi.wiki/view/Add-on:Radio
https://github.com/dersphere/plugin.audio.radio_de

b)Traductor Simultáneo
https://hipertextual.com/archivo/2013/11/traductor-raspberry-pi/

Integrantes:
-López Hernández Arim Daniel.
-Osuna León Paul Aram.
-Villagomez Gazca Miriam Judith.

**Comment by IoTeacher** [comment]
Se mueve a Gestion de proyectos.
