### ISSUE TITLE
Reunión de Planeación

### ISSUE THREAD

**Issue by KarenJacuinde** [tectijuana/interfaz#21]
Continuar con Etapa de Planeación - Terminar Wiki
@MarioMijes investigar case para raspberry PI
@WONG13 @mrjp94 Asignar Roles y Tareas

**Comment by MarioMijes** [comment]
Diseñando la case personalizada para la RaspberryPi

**Comment by mrjp94** [comment]
Asignación de Roles. 

Administrador plataforma web: Mrjp94 (Juan Pablo Salcedo)
Administrador de base de datos: @KarenJacuinde 
Desarollo de scripts para la Raspberry: @MarioMijes 
Configuracion de la Raspberry: @WONG13

**Comment by mrjp94** [comment]
![4affbe170b263556a03db432b6c0c2267adf36449441f436b03cdf812497801f](https://cloud.githubusercontent.com/assets/11907240/10471937/843c3b86-71cf-11e5-9146-a7b6ff6c16d2.jpg)

**Comment by WONG13** [comment]
Administrador plataforma web: Consiste en el desarrollo de la pagina web que se encargara de registrar y brindarle el acceso a los usuarios que tengan permiso de acceder al servidor de impresion de Raspberry PI.

Administrador de base de datos: Es el encargado del diseño y desarrollo de la base de datos en la cual se realizara el registro de los usuarios que tengan acceso al servidor de imprecion de Raspberry PI.

Desarrollo de scripts para la Raspberry: Su trabajo es el desarrollo de script que permita dar de alta el servicio de impresion de manera web, a si como la manipulacion de los archivos que se reciban para su impresion.

Configuracion de la Raspberry: Es el encargado de realizar todas las configuraciones necesarias  en la Raspberry PI, para dar de alta el servicio de impresion y la pagina que se encargara de brindar este servicio
