### ISSUE TITLE
Equipo Circuito cerrado de camaras

### ISSUE THREAD

**Issue by aquinin94** [tectijuana/interfaz#22]
Integrantes del Equipo
Aquino Vazquez Sergio Alan 
Flores Vizuet Daniel Alfonso

Proyecto
Elaborar un circuito cerrado de cámaras el cual podrá ser monitoreado desde cualquier dispositivo que esté conectado a internet.

**Comment by IoTeacher** [comment]
Evaluado parcialmente

**Comment by IoTeacher** [comment]
@aquinin94 y @13211476 con 100.
