### ISSUE TITLE
Proyecto Pushetta App via RPI

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#26]
# Documentar el wiki sobre la presentación del App final.

**Comment by IoTeacher** [comment]
## @gamerod y Juan Carlos Verde, con 100 en el proyecto final.

**Comment by IoTeacher** [comment]
Juan Carlos Verde con el WIKI

**Comment by Jcverdem** [comment]
integrantes:
     @gamerod 
     @jcverdem
pushetta nos permite la creación de canales y el envío de notificaciones al celular, las notificaciones push son un tipo de comunicación entre dispositivos donde es el servidor quien inicia la petición hacia el cliente cuando tiene una nueva notificación que enviar, permitiendo un ahorro de recursos respecto a otras tecnologías más convencionales. La tecnología push permite recibir los emails en un smartphone según van llegando al servidor de correo, cada vez que llega un email nuevo el servidor envía una notificación al celular para que lo descargue.
Se pueden  dar muchas aplicaciones a este tipo de servicios asi como estableser modulos de seguridad y mediante esta tecnologia dar alertas directas al smartphone.


![15292725_1263456367049838_1812046637_o](https://cloud.githubusercontent.com/assets/16808325/20689564/ea3dcb44-b57a-11e6-9728-f0bcacb445a8.png)

**Comment by IoTeacher** [comment]
Trabajando WIKI liberando
