### ISSUE TITLE
Reunion de Diseño

### ISSUE THREAD

**Issue by MarioMijes** [tectijuana/interfaz#32]
En esta etapa se diseñaran 3 aspectos del proyecto, Base de Datos, Scripts y Case de la Raspberry Pi 2.

**Comment by MarioMijes** [comment]
Reunion de Diseño, Observar el estado del SO de la raspberry, continua el diseño del case de la RPI

**Comment by KarenJacuinde** [comment]
Continuar con el diseño de la base de datos.
