### ISSUE TITLE
Instalacion de Software Necesario

### ISSUE THREAD

**Issue by 3liza** [tectijuana/interfaz#37]
Se instala el software necesario tanto en computadora como el Memoria

**Comment by Cardenassilveria** [comment]
Para realizar la instalacion de RaspBMC en la tarjeta SD desde Windows se requiere la instalacion de las siguientes herramientas
SDFormatter que se utiliza d para dejear preparada la SD para grabar la imagen
Win32DiskImager es utilizada para grabar el archivo de imagen
MiniTool Partition Wizard que permite redimensionar las particiones de la SD.
