### ISSUE TITLE
2.2.0  Cierre de Expos  (calificaciones semi-finales)

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#38]
# PRE-EVALUACION

## Falta preguntar a los equipos si alguien no expuso y los 3 equipos por exponer.

[TEMA1-LDI-idoceo_2pm-Interfaz_20240417.pdf](https://github.com/tectijuana/interfaz/files/15017261/TEMA1-LDI-idoceo_2pm-Interfaz_20240417.pdf)

**Comment by ROSY-SALAZAR33** [comment]
<script src="https://gist.github.com/ROSY-SALAZAR33/6cc30a483ecaa9e8af8c3cdbef6d6370.js"></script>
