### ISSUE TITLE
Depósito Repo Final 2pm

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#52]
![Screenshot 2024-05-19 at 17 09 08](https://github.com/tectijuana/interfaz/assets/2523851/fd43aaac-e9f1-4d4c-ba89-5163a3fadf44)

Favor de agregar IOTEACHER de tener "privado" su repositorio. o darme referencia de este para dar evaluación

**Comment by IoTeacher** [comment]
[LDI2pm Borrador Calculo  final (falta repo proy final).pdf](https://github.com/tectijuana/interfaz/files/15371312/LDI2pm.Borrador.Calculo.final.falta.repo.proy.final.pdf)

**Comment by KingVara2** [comment]
https://github.com/KingVara2/Los-bombas.git

**Comment by IoTeacher** [comment]
Se atendio
