### ISSUE TITLE
Examen de Unica Oportunidad (solo interesados Lunes puntuales)

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#55]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/d401909d-a2e1-4fd5-bcf1-87ee2675c101)

**Comment by IoTeacher** [comment]
Examen de unica oportunidad el dia 27 de mayo.

- Será en hoja impresa, 25 preguntas promedio abiertas. 
- Para pasar el examen ocupa 20 contestadas.
- Letra legible en lápiz no pluma
- será hoja blanca para diagramas
- 40 minutos

Resultados en la 3:30pm en GitHub

**Comment by AbnerOrterga98** [comment]
Profesor impartirá clases en línea mañana?

**Comment by IoTeacher** [comment]
Los resultados ya estan publicados

**Comment by AlvarezKevinDaniel** [comment]
Buen día profe, ¿el examen estará basado como en el que hicimos en la primera unidad?

**Comment by IoTeacher** [comment]
Todo lo que esta marcado en el PDF, de los proyectos se cuestionarà una parte.

**Comment by AlvarezKevinDaniel** [comment]
Disculpe pero, ¿cuál es el PDF?
