### ISSUE TITLE
Kardex Capturado (se borrara este  Project en Junio 15, 2024)

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#57]
# KARDEX CAPTURADO

**Comment by IoTeacher** [comment]
[LDI3pmKardex.pdf](https://github.com/tectijuana/interfaz/files/15475097/LDI3pmKardex.pdf)

**Comment by JosueJCC02** [comment]
Disculpe profe pero yo si le entregaba los trabajos en clase además nunca falte a su clase y pues la verdad no es justo

**Comment by IoTeacher** [comment]
Se atendieron las dudas personalmente en Lab D.

Semestre esta cerrado.
