### ISSUE TITLE
Configuracion SO

### ISSUE THREAD

**Issue by Cardenassilveria** [tectijuana/interfaz#58]
Se configura el internet y se realizan pruebas basicas

**Comment by Cardenassilveria** [comment]
Configuracion: Usando IPTV Simple Client en Kodi https://github.com/noquierouser/tavocles/wiki/Usando-IPTV-Simple-Client-en-Kodi

**Comment by Cardenassilveria** [comment]
transferir ficheros a tu media center Raspberry Pi
http://www.mimediacenter.info/2014/02/23/como-transferir-ficheros-a-tu-media-center-raspberry-pi/

**Comment by OsvaldoPerez** [comment]
Se termina la configuracion de la Raspberry Pi
