### ISSUE TITLE
1.1 Seleccionado Arquitectura ARM 64 bit

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/interfaz#8]
![image](https://github.com/tectijuana/interfaz/assets/2523851/84687433-4895-443b-84ba-6676d8ed9e02)

![Image](https://github.com/tectijuana/interfaz/assets/2523851/7ac05c1a-1477-43fe-9375-63d935aab8e4)

Favor de borrar las maquinas de pruebas de AWS Academy

a) Terminar y borrar todas las instancias de prueba
b) Invocar nuevo nodo Ubuntu en ARM Aquitectura
   colocando al final el bloque siguiente GIST:

https://gist.github.com/IoTeacher/6f25bb5efb9dfff4ae8a0f3651c31a4b

c) Acceder via VS Code con la extension SSH

---------------

![Image](https://github.com/tectijuana/interfaz/assets/2523851/78e040f8-d605-45d3-aeba-268eef6c52ea)

Lista de Cotejo,  Estudiantes envía 1 post de sus logros de esta practica de conocer la arquitectura ARM 64 bit

CITAS:
https://aws.amazon.com/es/blogs/aws/join-the-preview-for-new-memory-optimized-aws-graviton4-powered-amazon-ec2-instances-r8g/

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/4742cc68-6cf3-4158-9292-8a4109f5ea5b)

**Comment by Yahirs19** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105743054/60ede2bb-0981-471a-a379-51ad7b781e1a)



![Image](https://github.com/tectijuana/interfaz/assets/105743054/38660186-1470-4ec1-b174-453e90ef2c77)



![Image](https://github.com/tectijuana/interfaz/assets/105743054/268b5608-6e8e-4dda-a8fa-c1235f521a33)

**Comment by luissluu** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/144566345/814f583a-ec62-41da-b03d-13691135fa76)





![Image](https://github.com/tectijuana/interfaz/assets/144566345/dd84dbee-ec34-44ad-941f-b0d0778e31ab)





![Image](https://github.com/tectijuana/interfaz/assets/144566345/daee72b8-356d-40e7-91ad-c1823cedab88)



![Image](https://github.com/tectijuana/interfaz/assets/144566345/e85f11f8-a5fd-4fb0-a8c1-d22b27f42e44)

**Comment by SantyDebian** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158227698/c5d85efd-ba2e-4d55-9976-6412e4e0f18a)

![Image](https://github.com/tectijuana/interfaz/assets/158227698/8c0f13b3-4daf-4588-a55b-501b4d672660)
![Image](https://github.com/tectijuana/interfaz/assets/158227698/a6a98382-3377-4e7f-acdf-396f214ea779)
![Image](https://github.com/tectijuana/interfaz/assets/158227698/f898ce13-1668-4028-9d45-8825ccac4ce4)

**Comment by Shouko07** [comment]
![image](https://github.com/tectijuana/interfaz/assets/142704126/b0acf7ad-75cf-49a6-a0ad-67c494875125)
![Captura](https://github.com/tectijuana/interfaz/assets/142704126/258923af-80c9-4301-a2ad-b22a7128aa54)
![image](https://github.com/tectijuana/interfaz/assets/142704126/84a4a71e-e941-427e-8ff0-ce4b34a05571)

**Comment by AbrahamAganza** [comment]
Aganza Molina Abraham armando 
19210455
![Image](https://github.com/tectijuana/interfaz/assets/158363673/7f4dd7b9-d590-4ea1-8ab0-42f2b4566b7e)
![Image](https://github.com/tectijuana/interfaz/assets/158363673/b4cb9138-f083-489c-af2f-1bd7820dce6e)
![Image](https://github.com/tectijuana/interfaz/assets/158363673/268597d7-ac49-4cd4-af88-11f3f5d613da)

**Comment by RamiroMM21** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105456306/608c1802-6c60-49e1-9c32-1acc524caa9c)




![Image](https://github.com/tectijuana/interfaz/assets/105456306/6607ba77-ed0d-49a3-a2c4-12541438e86e)
![Image](https://github.com/tectijuana/interfaz/assets/105456306/7ca7c502-7286-4500-80f8-93b2a1d621c3)
![Image](https://github.com/tectijuana/interfaz/assets/105456306/236c00cd-dce5-4ee7-8271-e779b8ca1f9d)

**Comment by JulioHdez** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105742969/68a69fdc-06a5-4ac6-ae5e-56c31d542960)


![Image](https://github.com/tectijuana/interfaz/assets/105742969/2eeb109d-6051-4492-af5a-2a57156c26b9)
![Image](https://github.com/tectijuana/interfaz/assets/105742969/899aa721-e03d-409a-892a-527ab758f893)
![Image](https://github.com/tectijuana/interfaz/assets/105742969/9d84377e-e1d1-46f5-8275-a2b9fb6673bb)

**Comment by fragojor** [comment]
## Jorge Yahir Fragoso Arellano
![Image](https://github.com/tectijuana/interfaz/assets/158106293/a171ee85-b6b2-4c3b-ac1e-16c9912c7809)
![Image](https://github.com/tectijuana/interfaz/assets/158106293/a9b89e09-f047-42d6-85da-34c2646fd785)
![Image](https://github.com/tectijuana/interfaz/assets/158106293/136bab49-36cf-4cc0-810b-958d5805d553)

**Comment by MoralesBilli** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158227931/d5611dc9-e746-491f-ac38-98e6de068b5c)


![Image](https://github.com/tectijuana/interfaz/assets/158227931/4e28976d-fec1-42a3-b389-7dcd3bdd92d0)



![Image](https://github.com/tectijuana/interfaz/assets/158227931/118b5a45-8c19-4978-bfeb-115faa12eac9)



![Image](https://github.com/tectijuana/interfaz/assets/158227931/78df5eec-8498-4da5-92d1-918b8a96f00a)

**Comment by AbranEG** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158106702/7b308f9f-275a-4ab3-b2ee-bbcf367f385f)




![Image](https://github.com/tectijuana/interfaz/assets/158106702/ba5b94d0-bf42-4f5d-8320-4006b8ff0b7f)




![Image](https://github.com/tectijuana/interfaz/assets/158106702/0f4caac7-038d-4710-951b-4898d3fe3c2f)

**Comment by Thejimmy246** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158226731/710dab0e-2fc1-4880-82f5-1f2cb4529fc1)



![Image](https://github.com/tectijuana/interfaz/assets/158226731/c874c1e6-2e47-4c19-b3d4-dd32c896344e)





![Image](https://github.com/tectijuana/interfaz/assets/158226731/0480e442-5fba-422a-8f53-2c8e1c8eb7b5)

**Comment by KevinGarciaCo** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/147459383/2e31f202-6976-4ca5-8399-bf02a05451f7)



![Image](https://github.com/tectijuana/interfaz/assets/147459383/cae9e9ff-7abb-449c-a967-78540d78655c)



![Image](https://github.com/tectijuana/interfaz/assets/147459383/64301eae-2faf-4c3c-ae5e-8820616cdac8)



![Image](https://github.com/tectijuana/interfaz/assets/147459383/59b97eb5-6372-481d-975d-3f9a550a234a)

**Comment by EddieReynosoR** [comment]
# Reynoso Rosales Eduardo 21212036

![Image](https://github.com/tectijuana/interfaz/assets/105455890/de8b716b-671f-48fb-8349-8c192164e1fa)
![Image](https://github.com/tectijuana/interfaz/assets/105455890/b0371e7e-e159-4554-a6f5-481a1d3fa2f7)
![Image](https://github.com/tectijuana/interfaz/assets/105455890/d1c0a287-72bc-4957-ac7a-8a6479c30414)

**Comment by MelMolly** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158124690/fdae6c83-a854-4115-9a58-3f02c70a71b9)

**Comment by Pasillas07** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158227802/a30088ee-9d65-41e6-a446-d2bbf45fb26d)
![Image](https://github.com/tectijuana/interfaz/assets/158227802/1664e36d-fce3-4a01-b65e-f7ee611be453)

**Comment by Thejimmy246** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158226731/179a63a0-52fa-4c84-8f51-d497832cdcd9)



![Image](https://github.com/tectijuana/interfaz/assets/158226731/ecfcdc76-dae6-4d29-97f9-38d2e0924827)



![Image](https://github.com/tectijuana/interfaz/assets/158226731/9c380f56-b3a7-44c0-8f4c-1d90e3014a03)

**Comment by EduardoVazquez1881** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105814913/8be617d4-4df2-42ac-9c3c-82f12c0f875b)
![Image](https://github.com/tectijuana/interfaz/assets/105814913/5cad6b1c-d3f5-4cf3-9526-6ac8883aa171)

**Comment by ObedVPSM256** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105815117/1a4c0a7c-56c5-403e-b442-b21f9bad4a54)

![Image](https://github.com/tectijuana/interfaz/assets/105815117/b51a1c79-e623-4915-b080-adc803725d89)

![Image](https://github.com/tectijuana/interfaz/assets/105815117/312e7178-38a4-447c-9c39-a1b789849ce2)

**Comment by SebastianCamposI** [comment]
CAMPOS IBARRA SEBASTIAN


![Image](https://github.com/tectijuana/interfaz/assets/105455746/f2ca0abb-ba14-4cba-8a7c-37a4189a057e)



![Image](https://github.com/tectijuana/interfaz/assets/105455746/78d17253-87f1-4dc9-b342-443bebaec614)



![Image](https://github.com/tectijuana/interfaz/assets/105455746/20fd1e79-5ef6-47c5-a7c9-3fd4b28a87f6)

**Comment by Olaf-Huerta** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105456217/444ddd45-6e2b-445e-a7a5-c7b2dc5640e6)



![Image](https://github.com/tectijuana/interfaz/assets/105456217/db23780d-f655-454a-ae27-04793d3ecad8)



![Image](https://github.com/tectijuana/interfaz/assets/105456217/70657026-2cd8-4064-9142-26d404543a92)



![Image](https://github.com/tectijuana/interfaz/assets/105456217/00f5affc-62cc-4d2b-aea6-19ea5cc1acc5)

**Comment by LuisQuinnonez** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158366686/76800379-3c4a-4a5d-a0a8-5ef1d1076e19)



![Image](https://github.com/tectijuana/interfaz/assets/158366686/cbcb7c8e-9fce-4b32-8b7d-395835127bc8)



![Image](https://github.com/tectijuana/interfaz/assets/158366686/8f95e260-b7d3-41c4-9150-09701e942528)



![Image](https://github.com/tectijuana/interfaz/assets/158366686/ede91b7e-a448-4e1c-8aed-10c79f2d28b5)

**Comment by OscarBernardinoVeraCortez** [comment]
oscar vera cortez


![Image](https://github.com/tectijuana/interfaz/assets/126616060/e22a619c-e14f-4e77-8249-cff64db592bc)



![Image](https://github.com/tectijuana/interfaz/assets/126616060/32759f9d-e285-4cfa-9350-e3123e98c4cc)




![Image](https://github.com/tectijuana/interfaz/assets/126616060/df324c84-da63-42c0-8267-1f304bb93408)



![Image](https://github.com/tectijuana/interfaz/assets/126616060/affc42a5-066b-4a31-a138-114b117b8892)

**Comment by OscarBernardinoVeraCortez** [comment]
oscar vera cortez


![Image](https://github.com/tectijuana/interfaz/assets/126616060/e22a619c-e14f-4e77-8249-cff64db592bc)



![Image](https://github.com/tectijuana/interfaz/assets/126616060/32759f9d-e285-4cfa-9350-e3123e98c4cc)




![Image](https://github.com/tectijuana/interfaz/assets/126616060/df324c84-da63-42c0-8267-1f304bb93408)



![Image](https://github.com/tectijuana/interfaz/assets/126616060/affc42a5-066b-4a31-a138-114b117b8892)

**Comment by YessMtz** [comment]
### **MARTINEZ NAVA BLANCA YESSENIA**

![Image](https://github.com/tectijuana/interfaz/assets/105814773/92e14b9b-5ae3-4c83-8e7b-f4ce1be81ddf)
![Image](https://github.com/tectijuana/interfaz/assets/105814773/ff37be86-2d53-4f2a-bc26-52ed2fb998bc)
![Image](https://github.com/tectijuana/interfaz/assets/105814773/fa18327f-660f-42ff-8c10-781728e39602)

**Comment by cristianHernandezVITT** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/105743030/91cfb97e-a032-420a-b000-65db593e2fa5)



![Image](https://github.com/tectijuana/interfaz/assets/105743030/6740f29e-4a91-4c5d-93c8-64a508eb81bc)



![Image](https://github.com/tectijuana/interfaz/assets/105743030/6d1d6753-76fa-4dd8-9cd8-a0f27246a78a)

**Comment by SPerez84** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/114442048/6de8101a-8388-4ef8-b821-3eb76cd3b895)

**Comment by Eli-kopter** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158227726/bf3f3160-fc3c-4538-80e8-04686ce69e5d)





![Image](https://github.com/tectijuana/interfaz/assets/158227726/05ec139a-8ccd-4cdd-9e4f-60319b693b7b)





![Image](https://github.com/tectijuana/interfaz/assets/158227726/8e0efe95-5ebd-435c-bef1-8f407dd4737b)

**Comment by KingVara2** [comment]
**Ulises Andres Vara Espinoza 21212656**

![Image](https://github.com/tectijuana/interfaz/assets/158336615/4669cdc4-5cc4-451e-ae06-5b3d33b1699b)



![Image](https://github.com/tectijuana/interfaz/assets/158336615/9cb7416a-0e7f-4226-a91f-ba899121abf4)



![Image](https://github.com/tectijuana/interfaz/assets/158336615/e8a9c447-a6ee-46ea-80f2-d8ee0a8ddd1e)

**Comment by AdrianVC0411** [comment]
Valdés Cansino Adrián


![Image](https://github.com/tectijuana/interfaz/assets/158228308/ec7b83ce-c00e-4be3-8e48-50360691ce9b)



![Image](https://github.com/tectijuana/interfaz/assets/158228308/e44d92b4-2bb1-400e-be9c-9868c3407003)



![Image](https://github.com/tectijuana/interfaz/assets/158228308/cd007231-6943-4179-9ed5-689f260df87a)

**Comment by AbranEG** [comment]
**Abraham Ezequiel Garcia Campos 2121037**6
![image](https://gist.github.com/assets/158106702/38cd5712-3eb8-4a3e-9f49-19bad60983c5)
![image](https://gist.github.com/assets/158106702/48384be1-218a-40dc-a4be-163a96f6a847)
![image](https://gist.github.com/assets/158106702/bef7f1b9-453b-42d0-aaa7-ba3ceffd721b)

**Comment by IvanVG7** [comment]
Ivan Jair Vizcarra Gomez 21210676


![Image](https://github.com/tectijuana/interfaz/assets/158106662/a5b478d2-4eac-4a96-81e8-6a3f383fa890)



![Image](https://github.com/tectijuana/interfaz/assets/158106662/58baec6c-b6e0-4e91-889e-1df0e5f97232)



![Image](https://github.com/tectijuana/interfaz/assets/158106662/5d5e50c7-343c-4e1b-9bdd-bfdec0be8bbd)

**Comment by LuisFlores2121** [comment]
Luis Fernando Aguiñaga Flores - 21210354

![Image](https://github.com/tectijuana/interfaz/assets/114443206/96aac66a-03fa-4c69-9949-5493340a15bd)

![Image](https://github.com/tectijuana/interfaz/assets/114443206/85a30bfe-46c6-4c50-86f9-1f040ad67292)

![Image](https://github.com/tectijuana/interfaz/assets/114443206/4bdd7c60-5010-4f4a-84d6-ec414cc50911)

![Image](https://github.com/tectijuana/interfaz/assets/114443206/6540aafc-89e5-4260-9902-ba0151d526f7)

**Comment by AbnerOrterga98** [comment]
Ortega Medina Abner Nahum #20211819
![Image](https://github.com/tectijuana/interfaz/assets/158227565/8fa27637-2a94-4470-a13a-ea513f3beb5b)



![Image](https://github.com/tectijuana/interfaz/assets/158227565/2dca319e-f150-4857-becf-8d89b8bf5f89)



![Image](https://github.com/tectijuana/interfaz/assets/158227565/13bdbf42-ee39-484f-a493-f9a1c181604b)

**Comment by JuanFLuna25** [comment]
Juan Francisco Luna Bernal-21210393


![Image](https://github.com/tectijuana/interfaz/assets/144767878/072d8f12-5f80-40ac-9335-f9f845a8343d)
![Image](https://github.com/tectijuana/interfaz/assets/144767878/587e6f29-7cdd-4b83-a803-89d016d0820d)
![Image](https://github.com/tectijuana/interfaz/assets/144767878/8970e9b3-faaa-4ac2-80f7-a133d2a04434)

**Comment by JuanFloresFernandez** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/159850737/3429cbd1-f3c9-4f18-abcb-e6b1dc151316)

**Comment by MtzManuel** [comment]
Manuel Martinez 21210396 



![Image](https://github.com/tectijuana/interfaz/assets/158227866/e7493e4a-41ed-4374-adcf-9e108a4ffba3)
![Image](https://github.com/tectijuana/interfaz/assets/158227866/d9528b1b-af32-431e-93a4-e363fa3149be)
![Image](https://github.com/tectijuana/interfaz/assets/158227866/e20a1574-2337-45fc-b015-8d10dc4451e8)

**Comment by AmloEsMiDictador** [comment]
Perez González Kevin William l21212019


![Image](https://github.com/tectijuana/interfaz/assets/113724937/1f8572c6-3331-4aa9-9ca7-035b8eaae113)

![Image](https://github.com/tectijuana/interfaz/assets/113724937/c68d6ad5-6918-4800-b5b8-89ce10d476a1)

**Comment by Esmeghdez** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/158367928/1cbb2a0f-7337-46a5-9b4d-b480b252099f)



![Image](https://github.com/tectijuana/interfaz/assets/158367928/fe7c3534-b355-4e98-8639-025ecdbc3248)



![Image](https://github.com/tectijuana/interfaz/assets/158367928/cd2af1c5-bb74-454a-b2be-5a8a18c2da8c)



![Image](https://github.com/tectijuana/interfaz/assets/158367928/814ecc64-19c8-4bca-8ca1-ae2849a5fce5)



![Image](https://github.com/tectijuana/interfaz/assets/158367928/a95a4fde-eb51-4073-9977-c0b45bbb8d74)
